[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/var/lib/odoo/custom_addons
proxy_mode = True
xmlrpc_port = 8069

db_host = ep-blue-lab-aotglg70-pooler.c-2.ap-southeast-1.aws.neon.tech
db_port = 5432
db_user = neondb_owner
db_password = npg_HhtiFvSY8Cf6
db_name = neondb

log_level = info
logfile = False